### PR TITLE
Fix some bounds-arithmetic flaws in the tests, and update to quickcheck v1

### LINKED ISSUE #22: test::check_array_ref_5 and test::check_array_mut_ref_7 fail with quickcheck@1.0.3
I got some test failures when building this with Guix:

```
starting phase `check'

running 10 tests
test test::test_5_array_refs ... ok
test test::simple_case_works ... ok
test test::test_5_array_refs_dotdot ... ok
test test::test_5_mut_xarray_refs_with_dotdot ... ok
test test::test_5_mut_xarray_refs ... ok
test test::checks_bounds - should panic ... ok
test test::check_array_mut_ref_7 ... FAILED
test test::check_array_ref_5 ... FAILED
test test::check_array_mut_ref_out_of_bounds_32 ... ok
test test::check_array_ref_out_of_bounds_5 ... ok

failures:

---- test::check_array_mut_ref_7 stdout ----
thread 'test::check_array_mut_ref_7' panicked at 'slice index starts at 18446744073709551615 but ends at 6', src/lib.rs:370:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584bc1 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::h4def5818daceb913
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:249:13
  12:     0x555555584bc1 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::hfdc1139e9fcf277d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:26:9
  13:     0x555555584bc1 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h5b02cced783b6003
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2508:9
  14:     0x555555584bc1 - lib::test::check_array_mut_ref_7::f::h104bf1b38b2d044f
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:370:19
  15:     0x5555555855ab - <fn(A,B) .> T as quickcheck::tester::Testable>::result::{{closure}}::h8ae524f3f5695781
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:371:35
  16:     0x5555555855ab - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5e88cb9b50ac1085
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x5555555855ab - std::panicking::try::do_call::h886761d68f622e1d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x5555555855ab - std::panicking::try::h24277841a9084ec9
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x5555555855ab - std::panic::catch_unwind::hd9e31635d6ae42e5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x5555555855ab - quickcheck::tester::safe::h84b5e6dda4332f84
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x5555555855ab - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:371:21
  22:     0x5555555855ab - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  23:     0x5555555855ab - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  24:     0x5555555855ab - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  25:     0x7ffff7f58293 - <unknown>
  26:     0x7ffff7f5845b - <unknown>
  27:     0x7ffff7f6df75 - <unknown>
  28:     0x7ffff7f66d0f - <unknown>
  29:     0x7ffff7e250e3 - <unknown>
  30:     0x7ffff7d5dd7e - <unknown>
  31:     0x7ffff7b44eff - clone
  32:                0x0 - <unknown>
thread 'test::check_array_mut_ref_7' panicked at 'slice index starts at 18446744073709551615 but ends at 6', src/lib.rs:370:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584bc1 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::h4def5818daceb913
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:249:13
  12:     0x555555584bc1 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::hfdc1139e9fcf277d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:26:9
  13:     0x555555584bc1 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h5b02cced783b6003
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2508:9
  14:     0x555555584bc1 - lib::test::check_array_mut_ref_7::f::h104bf1b38b2d044f
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:370:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  23:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  24:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  25:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  26:     0x7ffff7f58293 - <unknown>
  27:     0x7ffff7f5845b - <unknown>
  28:     0x7ffff7f6df75 - <unknown>
  29:     0x7ffff7f66d0f - <unknown>
  30:     0x7ffff7e250e3 - <unknown>
  31:     0x7ffff7d5dd7e - <unknown>
  32:     0x7ffff7b44eff - clone
  33:                0x0 - <unknown>
thread 'test::check_array_mut_ref_7' panicked at 'slice index starts at 18446744073709551615 but ends at 6', src/lib.rs:370:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584bc1 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::h4def5818daceb913
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:249:13
  12:     0x555555584bc1 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::hfdc1139e9fcf277d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:26:9
  13:     0x555555584bc1 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h5b02cced783b6003
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2508:9
  14:     0x555555584bc1 - lib::test::check_array_mut_ref_7::f::h104bf1b38b2d044f
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:370:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  24:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  25:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  26:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  27:     0x7ffff7f58293 - <unknown>
  28:     0x7ffff7f5845b - <unknown>
  29:     0x7ffff7f6df75 - <unknown>
  30:     0x7ffff7f66d0f - <unknown>
  31:     0x7ffff7e250e3 - <unknown>
  32:     0x7ffff7d5dd7e - <unknown>
  33:     0x7ffff7b44eff - clone
  34:                0x0 - <unknown>
thread 'test::check_array_mut_ref_7' panicked at 'slice index starts at 18446744073709551615 but ends at 6', src/lib.rs:370:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584bc1 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::h4def5818daceb913
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:249:13
  12:     0x555555584bc1 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::hfdc1139e9fcf277d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:26:9
  13:     0x555555584bc1 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h5b02cced783b6003
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2508:9
  14:     0x555555584bc1 - lib::test::check_array_mut_ref_7::f::h104bf1b38b2d044f
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:370:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  25:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  26:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  27:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  28:     0x7ffff7f58293 - <unknown>
  29:     0x7ffff7f5845b - <unknown>
  30:     0x7ffff7f6df75 - <unknown>
  31:     0x7ffff7f66d0f - <unknown>
  32:     0x7ffff7e250e3 - <unknown>
  33:     0x7ffff7d5dd7e - <unknown>
  34:     0x7ffff7b44eff - clone
  35:                0x0 - <unknown>

[output removed to satify GitHub length limits]


thread 'test::check_array_ref_5' panicked at 'slice index starts at 18446744073709551612 but ends at 1', src/lib.rs:345:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584aa8 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h2289c8ca92f60312
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:238:13
  12:     0x555555584aa8 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h366e3001b7ab1da5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:15:9
  13:     0x555555584aa8 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h27911efe16c63359
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2496:9
  14:     0x555555584aa8 - lib::test::check_array_ref_5::f::h1bff3468a7381110
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:345:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  25:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  26:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  27:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  28:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  29:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  30:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  31:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  32:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  33:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  34:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  35:     0x7ffff7f58293 - <unknown>
  36:     0x7ffff7f5845b - <unknown>
  37:     0x7ffff7f6df75 - <unknown>
  38:     0x7ffff7f66d0f - <unknown>
  39:     0x7ffff7e250e3 - <unknown>
  40:     0x7ffff7d5dd7e - <unknown>
  41:     0x7ffff7b44eff - clone
  42:                0x0 - <unknown>
thread 'test::check_array_ref_5' panicked at 'slice index starts at 18446744073709551612 but ends at 1', src/lib.rs:345:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584aa8 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h2289c8ca92f60312
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:238:13
  12:     0x555555584aa8 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h366e3001b7ab1da5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:15:9
  13:     0x555555584aa8 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h27911efe16c63359
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2496:9
  14:     0x555555584aa8 - lib::test::check_array_ref_5::f::h1bff3468a7381110
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:345:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  25:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  26:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  27:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  28:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  29:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  30:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  31:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  32:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  33:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  34:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  35:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  36:     0x7ffff7f58293 - <unknown>
  37:     0x7ffff7f5845b - <unknown>
  38:     0x7ffff7f6df75 - <unknown>
  39:     0x7ffff7f66d0f - <unknown>
  40:     0x7ffff7e250e3 - <unknown>
  41:     0x7ffff7d5dd7e - <unknown>
  42:     0x7ffff7b44eff - clone
  43:                0x0 - <unknown>
thread 'test::check_array_ref_5' panicked at 'slice index starts at 18446744073709551612 but ends at 1', src/lib.rs:345:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584aa8 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h2289c8ca92f60312
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:238:13
  12:     0x555555584aa8 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h366e3001b7ab1da5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:15:9
  13:     0x555555584aa8 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h27911efe16c63359
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2496:9
  14:     0x555555584aa8 - lib::test::check_array_ref_5::f::h1bff3468a7381110
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:345:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  25:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  26:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  27:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  28:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  29:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  30:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  31:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  32:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  33:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  34:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  35:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  36:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  37:     0x7ffff7f58293 - <unknown>
  38:     0x7ffff7f5845b - <unknown>
  39:     0x7ffff7f6df75 - <unknown>
  40:     0x7ffff7f66d0f - <unknown>
  41:     0x7ffff7e250e3 - <unknown>
  42:     0x7ffff7d5dd7e - <unknown>
  43:     0x7ffff7b44eff - clone
  44:                0x0 - <unknown>
thread 'test::check_array_ref_5' panicked at 'slice index starts at 18446744073709551611 but ends at 0', src/lib.rs:345:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584aa8 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h2289c8ca92f60312
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:238:13
  12:     0x555555584aa8 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h366e3001b7ab1da5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:15:9
  13:     0x555555584aa8 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h27911efe16c63359
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2496:9
  14:     0x555555584aa8 - lib::test::check_array_ref_5::f::h1bff3468a7381110
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:345:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  25:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  26:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  27:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  28:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  29:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  30:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  31:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  32:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  33:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  34:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  35:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  36:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  37:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  38:     0x7ffff7f58293 - <unknown>
  39:     0x7ffff7f5845b - <unknown>
  40:     0x7ffff7f6df75 - <unknown>
  41:     0x7ffff7f66d0f - <unknown>
  42:     0x7ffff7e250e3 - <unknown>
  43:     0x7ffff7d5dd7e - <unknown>
  44:     0x7ffff7b44eff - clone
  45:                0x0 - <unknown>
thread 'test::check_array_ref_5' panicked at 'slice index starts at 18446744073709551611 but ends at 0', src/lib.rs:345:19
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x7ffff7e34450 - <unknown>
   7:     0x7ffff7e33744 - <unknown>
   8:     0x7ffff7e15402 - rust_begin_unwind
   9:     0x7ffff7df5681 - core::panicking::panic_fmt::h964c785332841a13
  10:     0x7ffff7df5532 - core::slice::index::slice_index_order_fail::h1412dd7fc43dcc0e
  11:     0x555555584aa8 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index::h2289c8ca92f60312
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:238:13
  12:     0x555555584aa8 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h366e3001b7ab1da5
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/slice/index.rs:15:9
  13:     0x555555584aa8 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h27911efe16c63359
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/alloc/src/vec/mod.rs:2496:9
  14:     0x555555584aa8 - lib::test::check_array_ref_5::f::h1bff3468a7381110
                               at /tmp/guix-build-rust-arrayref-0.3.6.drv-0/arrayref-0.3.6/src/lib.rs:345:19
  15:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::{{closure}}::hb746f8e9f169aa86
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:47
  16:     0x55555558631b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h55852fd405afa52a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/core/src/panic/unwind_safe.rs:271:9
  17:     0x55555558631b - std::panicking::try::do_call::h42827ae1928a5880
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:403:40
  18:     0x55555558631b - std::panicking::try::h50f30c76a6b2ed5e
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:367:19
  19:     0x55555558631b - std::panic::catch_unwind::h9464b0b1d1f1ebff
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panic.rs:133:14
  20:     0x55555558631b - quickcheck::tester::safe::hceee961432921080
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:402:5
  21:     0x55555558631b - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:349:33
  22:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  23:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  24:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  25:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  26:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  27:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  28:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  29:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  30:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  31:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  32:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  33:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  34:     0x5555555867b2 - <fn(A,B) .> T as quickcheck::tester::Testable>::result::shrink_failure::had6e83d413f85e4f
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:358:34
  35:     0x5555555857dd - <fn(A,B) .> T as quickcheck::tester::Testable>::result::h61902dc1d21e279b
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:380:17
  36:     0x5555555857dd - quickcheck::tester::QuickCheck::quicktest::hd39445620dbf3a10
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:121:19
  37:     0x5555555857dd - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:163:36
  38:     0x5555555857dd - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  39:     0x7ffff7f58293 - <unknown>
  40:     0x7ffff7f5845b - <unknown>
  41:     0x7ffff7f6df75 - <unknown>
  42:     0x7ffff7f66d0f - <unknown>
  43:     0x7ffff7e250e3 - <unknown>
  44:     0x7ffff7d5dd7e - <unknown>
  45:     0x7ffff7b44eff - clone
  46:                0x0 - <unknown>
thread 'test::check_array_ref_5' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([], 18446744073709551611)
Error: "slice index starts at 18446744073709551611 but ends at 0"', /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:165:28
stack backtrace:
   0:     0x7ffff7e3361c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7767eb774a4d4f42
   1:     0x7ffff7ec4bfc - core::fmt::write::hf3fb1fb91b38bb59
   2:     0x7ffff7e01bd5 - <unknown>
   3:     0x7ffff7e151bb - <unknown>
   4:     0x7ffff7e14d61 - <unknown>
   5:     0x7ffff7e1598b - std::panicking::rust_panic_with_hook::h19ec2b337ecb8872
   6:     0x555555586f7b - std::panicking::begin_panic::{{closure}}::hcc6d251cae549ad1
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:544:9
   7:     0x555555586f3c - std::sys_common::backtrace::__rust_end_short_backtrace::h24d9030f6caccc3a
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/sys_common/backtrace.rs:139:18
   8:     0x555555581270 - std::panicking::begin_panic::ha99dd9213600a59d
                               at /tmp/guix-build-rust-1.57.0.drv-0/rustc-1.57.0-src/library/std/src/panicking.rs:543:12
   9:     0x555555585cf2 - quickcheck::tester::QuickCheck::quickcheck::h648196ccb7ad4fcd
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:165:28
  10:     0x555555585cf2 - quickcheck::tester::quickcheck::hc490cc702c94f14d
                               at /tmp/guix-build-rust-quickcheck-1.0.3.drv-0/quickcheck-1.0.3/src/tester.rs:183:5
  11:     0x7ffff7f58293 - <unknown>
  12:     0x7ffff7f5845b - <unknown>
  13:     0x7ffff7f6df75 - <unknown>
  14:     0x7ffff7f66d0f - <unknown>
  15:     0x7ffff7e250e3 - <unknown>
  16:     0x7ffff7d5dd7e - <unknown>
  17:     0x7ffff7b44eff - clone
  18:                0x0 - <unknown>


failures:
    test::check_array_mut_ref_7
    test::check_array_ref_5

test result: FAILED. 8 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.98s

error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "/gnu/store/xcimccp900ck56h1jwc1ahznrnj5l9jk-rust-arrayref-0.3.6-tests/bin/arrayref-embedded-tests" arguments: () exit-status: 101 term-signal: #f stop-signal: #f> 
phase `check' failed after 3.0 seconds
command "/gnu/store/xcimccp900ck56h1jwc1ahznrnj5l9jk-rust-arrayref-0.3.6-tests/bin/arrayref-embedded-tests" failed with status 101

```

Possibly this is due to using another version of quickcheck (we prefer to only use the latest version for simplicity, and some old versions fail to build), but if not this looks serious.

### PR DESCRIPTION
**Pull request by musicinmybrain**
Some tests relied on unsigned arithmetic that could wrap around, and quickcheck 1.0 was able to reveal the problem. All of the issues were in the tests rather than in the implementation.

Fixes https://github.com/droundy/arrayref/issues/22. Fixes compatibility with quickcheck v1.

The second commit actually updates the `quickcheck` dev-dependency to 1.0.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -339,7 +339,7 @@ mod test {
     #[test]
     fn check_array_ref_5() {
         fn f(data: Vec<u8>, offset: usize) -> quickcheck::TestResult {
-            if data.len() < offset + 5 {
+            if data.len() < 5 || data.len() - 5 < offset {
```
Comment (droundy) [inline src/lib.rs:342]: **suggestion:** I think this would be clearer with `checked_add`.

My brain hurts just a bit when trying to understand this logical combination, and if I hadn't read your description it wouldn't have been obvious that you were dealing with overflow.
```suggestion
            if data.len() < offset.checked_add(5).unwrap_or_default() {
```
Does this feel more clear to you also? If so, could you make this change to all of these?

**Review by droundy — APPROVED** [review]
Thanks so much for tracking this down and making this fix.  Impressive!

I'll give it a week or so and will just merge as is if you haven't responded.  (I know I could make the change myself, but seems nicer to let you have the decision since you did the work!)

File: src/lib.rs (hunk 1 above)
Comment (musicinmybrain) [reply src/lib.rs:342]: The suggestion to try to use a `*_add` method with more appropriate behavior rather than plain `+` or `-` for readability is a reasonable one. Unfortunately, it doesn’t look like this suggestion is logically equivalent.

Consider the case where `usize` is 64-bit, `data.len()` is `3` and `offset` is `usize::MAX - 2`, i.e. `0xfffffffffffffffe` or `18446744073709551614`. Then considering the intent of the original `data.len() < offset + 5`, we want the result to be `true`.

- The original expression `data.len() < offset + 5` got this wrong; `0xfffffffffffffffe + 5` wraps around to `3`, so the comparison is `5 < 3`, which is `false`.
- In `data.len() < 5 || data.len() - 5 < offset`, the first condition short-circuits to `true`: if `data.len()` is smaller than `5`, it must be less than the (mathematical, unbounded) sum of `5` and any nonnegative offset. Then the remaining comparison is written in a way that uses the reduction in the domain of `data.len()` due to the first condition to make wrapping impossible.
- In `offset.checked_add(5).unwrap_or_default()`, overflow is detected, so the `Option<usize>` is `None`, and so `.unwrap_or_default()` gives us `0`. The comparison is `5 < 0`, which is `false` – the same flaw as the original code, arrived at in a different way.

I do understand that it’s not obvious at a glance that `if data.len() < 5 || data.len() - 5 < offset` is an overflow-proof version of the idea in `data.len() < offset + 5` – some programmers accustomed to dealing with this in languages like C or C++ will recognize the pattern, but it still requires some thought to recognize the intent. I’ll think about whether there is a correct, obvious-looking way to express this with one of the a `*_add` methods, or whether perhaps it’s better to just add brief explanatory comments to these awkward conditionals.

Comment (musicinmybrain) [reply src/lib.rs:342]: In general, the difficulty in a simple fallback without rearranging the comparison is that when overflow occurs, we still need to evaluate the expression correctly, without discarding information from the operands, and one way or the other this tends to lead to needing to express it twice in perhaps slightly unnatural ways. But I’ll keep thinking about clever alternatives.

Comment (musicinmybrain) [reply src/lib.rs:342]: Even considering other methods like `.saturating_sub()`, I can’t think of a way to do this with `.<foo>_add.unwrap_or_<bar>()`. Anything I can think of has to have some kind of branch leading to the final Boolean result instead. It’s possible I am missing a trick, but I think it’s unlikely I’m missing one that’s more legible than the original suggestion.

For now, I’m just going to add comments to these four expressions, but if you have any other suggestions, I’m happy to try to prove/disprove their logical equivalence.
